# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go
name: build

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**/README.md'
      - '**/bench/**'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      FORCE_COLOR: 1
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: false
          fetch-depth: 0
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22.0'
          check-latest: true
          cache-dependency-path: "**/*.sum"
      - run: go version
      - name: Vendoring and Tidy
        run: go mod tidy && go mod vendor
      - name: Install dependencies
        run: |
          go install github.com/ory/go-acc@latest
      - name: Run tests
        run: |
          go-acc ./... -o coverage.out --ignore goaktpb,mocks,internal/internalpb,bench -- -mod=vendor -race -v
      - uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.out
          fail_ci_if_error: false
          verbose: true
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '>=1.22.0'
          check-latest: true
          cache-dependency-path: "**/*.sum"
      - name: Run Revive Action by pulling pre-built image
        uses: docker://morphy/revive-action:v2
        with:
          # Path to your Revive config within the repo (optional)
          config: build/revive.toml
